server:
  port: 8083

spring:
  application:
    name: service-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: consumer-8083
    prefer-ip-address: true

# Ribbon 负载均衡（可选）
ribbon:
  eureka:
    enabled: true

